Matrix

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -2,7 +2,7 @@ name: 15 - Working with Matrices
 on: 
   workflow_dispatch:
     inputs:
-      fail-fats:
+      fail-fast:
         type: boolean
         default: true
 
@@ -12,7 +12,7 @@ jobs:
         name: ${{matrix.os}}-${{matrix.node_version}}
         runs-on: ${{matrix.os}}
         strategy:     
-          fail-fast: ${{ inputs.fail-fats }}
+          fail-fast: ${{ inputs.fail-fast }}
           matrix:
             node_version: [18.x, 20.x, 21.x]
             os: 
@@ -29,9 +29,9 @@ jobs:
               uses: actions/setup-node@v4
               with:
                 node-version: ${{matrix.node_version}}
-            - name: Fail if experimental
-              if: ${{ matrix.tag == 'experimental' }}
-              run: exit 1
+            # - name: Fail if experimental
+            #   if: ${{ matrix.tag == 'experimental' }}
+            #   run: exit 1
             - name: Perform some tests
               run: |
                 echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node_version}}"
